### ISSUE TITLE
Wrong json url for C3D2 

### ISSUE THREAD

**Issue by blastmaster** [slopjong/OpenSpaceDirectory#11]
I could not add our space because it's already in the directory.  
https://github.com/SpaceApi/OpenSpaceDirectory/blob/master/directory.json
Unfortunately the url points to some  "no: space" json.
The correct url for C3D2 GCHQ is
http://www.hq.c3d2.de/spaceapi.json

please can you fix this

**Comment by slopjong** [comment]
Thx for your notice, I've just moved and couldn't work on this issue so far. I'll come back to you this weekend.

**Comment by slopjong** [comment]
Fixed in https://spaceapi.net/directory.json.

**Comment by astro** [comment]
Still not showing up. :-(

**Comment by astro** [comment]
Any updates?

**Comment by slopjong** [comment]
I'm sorry that it's taking so long already. I haven't had much internet since June 30th and wasn't able to do anything but working, riding the public transit and sleeping. 

I've bought a very crappy car today to reduce the travelling time from 3.5-4 **hours** to only 30 **min** per day. Please ping me on Saturday again, I've got other stuff to do in the meantime.

I'm getting a reliable (fix) internet connection next week since the mobile thingie is slow as f*ck if present at all due to my incredible good isolating appartment.

**Comment by astro** [comment]
Can I help you with a pull request that you can just merge? I mean, it was working fine before.

I hope things get more relaxed on your side.

**Comment by astro** [comment]
I hope you're doing better. One full hackerspace is prepared to jump in and help out if you can tell us where to start.

**Comment by slopjong** [comment]
Can we have a mumble/skype/whatever session this week?

directory.json is a static file but it's regenerated once per day during the revalidation process so this issue can't be fixed by simply editing the JSON. Some time back I started to migrate the old code base to the zend framework.

The revalidator/cache consists of a cronjob which goes through the whole list which doesn't scale well. It's a single point of failure so I/we need to redesign this service to make it (more) reliable.

When are you available for a chat?

**Comment by astro** [comment]
Add me on Jabber: astro@spaceboyz.net

**Comment by astro** [comment]
Is there a spec for the implementation? I could do it in node.js, Haskell, or Erlang. What's your preference?

**Comment by slopjong** [comment]
Sorry to come back to you so late. Did you change the value of the space field? That can be the only cause that your endpoint is always dropped. I'll fix it today.

**Comment by astro** [comment]
Yes, once last December. That would be totally awesome!

**Comment by slopjong** [comment]
It's fixed.

**Comment by astro** [comment]
W00t! You're the best!
