### ISSUE TITLE
Change request for URL

### ISSUE THREAD

**Issue by Bouni** [slopjong/OpenSpaceDirectory#21]
Hi,

I'm not sure if i got that right, but i need you to change the URL of our hackerspace **Reaktor23**:

At the moment it is: http://reaktor23.org/state/json.php
The new one is: http://spaceapi.reaktor23.org/spaceapi

**Comment by slopjong** [comment]
Done.

**Comment by Bouni** [comment]
Thanks!

**Comment by Bouni** [comment]
I just recognized that the spaceapi directory lists a wrong URL now:
"Reaktor 23":"http://spaceapi.net/cache/Reaktor+23"

Why?

**Comment by slopjong** [comment]
Your endpoint possibly might not have been reachable during the revalidation at that time. Your endpoint URL has been reinserted automatically last night.

I experience something weird with your endpoint in firefox (using a proxy). It can access the web but not your endpoint. This doesn't happen with chromium, cURL and wget. Any explanation for this? It's no firewall thing on my side but  

![2014-11-21-093709_628x333_scrot](https://cloud.githubusercontent.com/assets/456443/5138579/6707f304-7151-11e4-9604-e3f2edf94e05.png)

## One moment later

You changed your DNS record but didn't reduce the TTL before and that's why the directory temporarily pointed to the cache. And that's the reason why firefox can't access it.

Old DNS record:

```
# host spaceapi.reaktor23.org 
spaceapi.reaktor23.org is an alias for bdstr.ddns.reaktor23.org.
bdstr.ddns.reaktor23.org has address 77.3.131.9
```

New DNS record:

```
# host spaceapi.reaktor23.org         
spaceapi.reaktor23.org is an alias for bdstr.ddns.reaktor23.org.
bdstr.ddns.reaktor23.org has address 95.112.202.39
```

**Comment by Bouni** [comment]
One of my Hackerspace fellows found a problem with the DNS record and fixed it about n hour ago!
That was the problem! I didn't know that you revalidate the URL automatically and use a cache if it fails.

How long does it take to revalidate again?

**Comment by slopjong** [comment]
If the revalidator worked correctly it would retry 2 minutes after the first fail, then 5 minutes after the second fail, then 15 min after the next fail, then 30 min after the next fail, then 1h after the next fail, then 2h after the next fail, then 4 after the next fail, then 8h after the next fail, then 12 after the next fail and finally on a daily basis if the endpoint doesn't get fixed.

That's how it should work. As of now it's on a daily basis because of a bug.
